plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
remote_theme: pages-themes/midnight@v0.2.0
include:
  - index.md
  - eighttakeawayskilian/article.md